"""Raw ctypes binding for the JPL Moshier Ephemeris C API."""

from __future__ import annotations

from collections.abc import Iterable
from ctypes import (
    CDLL,
    POINTER,
    byref,
    c_char,
    c_char_p,
    c_double,
    c_int,
    c_size_t,
    c_uint,
    create_string_buffer,
)
from pathlib import Path

from ._loader import find_library, load_calceph_runtime

_SIGNATURES = {
    'jme_body_id_from_name': (c_int, [c_char_p]),
    'jme_body_naif_id': (c_int, [c_int]),
    'jme_body_name': (c_char_p, [c_int]),
    'jme_calc': (c_int, [c_double, c_int, c_int, POINTER(c_double), c_char_p]),
    'jme_calc_pctr': (c_int, [c_double, c_int, c_int, c_int, POINTER(c_double), c_char_p]),
    'jme_calc_ut': (c_int, [c_double, c_int, c_int, POINTER(c_double), c_char_p]),
    'jme_calendar_is_leap_year': (c_int, [c_int, c_int]),
    'jme_centiseconds_difference': (c_int, [c_int, c_int]),
    'jme_centiseconds_difference_signed': (c_int, [c_int, c_int]),
    'jme_centiseconds_normalize': (c_int, [c_int]),
    'jme_centiseconds_round_second': (c_int, [c_int]),
    'jme_centiseconds_to_degree_string': (c_char_p, [c_int, c_char_p]),
    'jme_centiseconds_to_lonlat_string': (c_char_p, [c_int, c_char_p]),
    'jme_centiseconds_to_time_string': (c_char_p, [c_int, c_char_p]),
    'jme_close': (None, []),
    'jme_copy_body_name': (c_char_p, [c_int, c_char_p]),
    'jme_date_is_valid': (c_int, [c_int, c_int, c_int, c_int]),
    'jme_day_of_week': (c_int, [c_double]),
    'jme_day_of_year': (c_int, [c_int, c_int, c_int, c_int]),
    'jme_days_in_month': (c_int, [c_int, c_int, c_int]),
    'jme_decimal_hour': (c_double, [c_int, c_int, c_double]),
    'jme_degree_midpoint': (c_double, [c_double, c_double]),
    'jme_degree_normalize': (c_double, [c_double]),
    'jme_degrees_difference': (c_double, [c_double, c_double]),
    'jme_degrees_difference_signed': (c_double, [c_double, c_double]),
    'jme_degrees_to_hours': (c_double, [c_double]),
    'jme_degrees_to_radians': (c_double, [c_double]),
    'jme_delta_t': (c_double, [c_double]),
    'jme_delta_t_ex': (c_double, [c_double, c_int, c_char_p]),
    'jme_double_to_long': (c_int, [c_double]),
    'jme_ecliptic_to_equatorial': (None, [c_double, c_double, c_double, POINTER(c_double), POINTER(c_double)]),
    'jme_ecliptic_to_equatorial_rectangular_state': (c_int, [POINTER(c_double), c_double, POINTER(c_double)]),
    'jme_elp2000_moon_state': (c_int, [c_double, POINTER(c_double)]),
    'jme_ephemeris_path': (c_char_p, []),
    'jme_equatorial_to_ecliptic': (None, [c_double, c_double, c_double, POINTER(c_double), POINTER(c_double)]),
    'jme_equatorial_to_ecliptic_rectangular_state': (c_int, [POINTER(c_double), c_double, POINTER(c_double)]),
    'jme_equatorial_to_horizontal': (None, [c_double, c_double, c_double, POINTER(c_double), POINTER(c_double)]),
    'jme_fixstar': (c_int, [c_char_p, c_double, c_int, POINTER(c_double), c_char_p]),
    'jme_fixstar_mag': (c_int, [c_char_p, POINTER(c_double), c_char_p]),
    'jme_fixstar_ut': (c_int, [c_char_p, c_double, c_int, POINTER(c_double), c_char_p]),
    'jme_fixstar2': (c_int, [c_char_p, c_double, c_int, POINTER(c_double), c_char_p]),
    'jme_fixstar2_mag': (c_int, [c_char_p, POINTER(c_double), c_char_p]),
    'jme_fixstar2_ut': (c_int, [c_char_p, c_double, c_int, POINTER(c_double), c_char_p]),
    'jme_gauquelin_sector': (c_int, [c_double, c_int, c_char_p, c_int, c_int, POINTER(c_double), c_double, c_double, POINTER(c_double), c_char_p]),
    'jme_get_astro_models': (c_int, [c_char_p, c_int]),
    'jme_get_ayanamsa': (c_double, [c_double]),
    'jme_get_ayanamsa_ex': (c_int, [c_double, c_int, POINTER(c_double), c_char_p]),
    'jme_get_ayanamsa_ex_ut': (c_int, [c_double, c_int, POINTER(c_double), c_char_p]),
    'jme_get_ayanamsa_name': (c_char_p, [c_int]),
    'jme_get_ayanamsa_ut': (c_double, [c_double]),
    'jme_get_frame_bias_matrix': (c_int, [c_int, POINTER(c_double)]),
    'jme_get_nutation': (c_int, [c_double, c_int, POINTER(c_double), POINTER(c_double), c_char_p]),
    'jme_get_nutation_matrix': (None, [c_double, c_double, c_double, POINTER(c_double)]),
    'jme_get_obliquity': (c_int, [c_double, c_int, POINTER(c_double), c_char_p]),
    'jme_get_orbital_elements': (c_int, [c_double, c_int, c_int, POINTER(c_double), c_char_p]),
    'jme_get_precession_matrix': (c_int, [c_double, c_double, c_int, POINTER(c_double)]),
    'jme_get_sidereal_mode': (None, [POINTER(c_int), POINTER(c_double), POINTER(c_double)]),
    'jme_get_tid_acc': (c_double, []),
    'jme_get_topo_pos': (c_int, [c_double, POINTER(c_double), c_char_p]),
    'jme_heliacal_angle': (c_double, [c_double, POINTER(c_double), POINTER(c_double), c_char_p]),
    'jme_heliacal_pheno_ut': (c_int, [c_double, POINTER(c_double), POINTER(c_double), c_char_p]),
    'jme_heliacal_ut': (c_int, [c_double, POINTER(c_double), POINTER(c_double), c_char_p]),
    'jme_helio_cross': (c_int, [c_int, c_double, c_double, c_int, POINTER(c_double), c_char_p]),
    'jme_helio_cross_ut': (c_int, [c_int, c_double, c_double, c_int, POINTER(c_double), c_char_p]),
    'jme_horizontal_to_equatorial': (None, [c_double, c_double, c_double, POINTER(c_double), POINTER(c_double)]),
    'jme_hours_normalize': (c_double, [c_double]),
    'jme_hours_to_degrees': (c_double, [c_double]),
    'jme_house_pos': (c_double, [c_double, c_double, c_double, c_int, POINTER(c_double), c_char_p]),
    'jme_house_system_name': (c_char_p, [c_int]),
    'jme_houses': (c_int, [c_double, c_double, c_double, c_int, POINTER(c_double), POINTER(c_double)]),
    'jme_houses_armc': (c_int, [c_double, c_double, c_double, c_int, POINTER(c_double), POINTER(c_double)]),
    'jme_houses_armc_ex2': (c_int, [c_double, c_double, c_double, c_int, POINTER(c_double), POINTER(c_double), POINTER(c_double), POINTER(c_double)]),
    'jme_houses_ex': (c_int, [c_double, c_int, c_double, c_double, c_int, POINTER(c_double), POINTER(c_double)]),
    'jme_houses_ex2': (c_int, [c_double, c_int, c_double, c_double, c_int, POINTER(c_double), POINTER(c_double), POINTER(c_double), POINTER(c_double)]),
    'jme_jd_add_seconds': (c_double, [c_double, c_double]),
    'jme_jd_difference_seconds': (c_double, [c_double, c_double]),
    'jme_jd_to_utc': (None, [c_double, c_int, POINTER(c_int), POINTER(c_int), POINTER(c_int), POINTER(c_int), POINTER(c_int), POINTER(c_double)]),
    'jme_jpl_body_state': (c_int, [c_double, c_int, c_int, c_int, POINTER(c_double), c_char_p]),
    'jme_jpl_body_state_naif': (c_int, [c_double, c_int, c_int, c_int, POINTER(c_double), c_char_p]),
    'jme_jpl_body_state_native': (c_int, [c_double, c_int, c_int, POINTER(c_double), c_char_p]),
    'jme_jpl_body_state_native_naif': (c_int, [c_double, c_int, c_int, POINTER(c_double), c_char_p]),
    'jme_jpl_body_state_native_split': (c_int, [c_double, c_double, c_int, c_int, POINTER(c_double), c_char_p]),
    'jme_jpl_body_state_native_split_naif': (c_int, [c_double, c_double, c_int, c_int, POINTER(c_double), c_char_p]),
    'jme_jpl_body_state_order': (c_int, [c_double, c_double, c_int, c_int, c_int, c_int, POINTER(c_double), c_char_p]),
    'jme_jpl_body_state_order_naif': (c_int, [c_double, c_double, c_int, c_int, c_int, c_int, POINTER(c_double), c_char_p]),
    'jme_jpl_body_state_split': (c_int, [c_double, c_double, c_int, c_int, c_int, POINTER(c_double), c_char_p]),
    'jme_jpl_body_state_split_naif': (c_int, [c_double, c_double, c_int, c_int, c_int, POINTER(c_double), c_char_p]),
    'jme_jpl_body_state_utc': (c_int, [c_int, c_int, c_int, c_int, c_int, c_double, c_int, c_int, c_int, c_int, POINTER(c_double), c_char_p]),
    'jme_jpl_body_state_utc_naif': (c_int, [c_int, c_int, c_int, c_int, c_int, c_double, c_int, c_int, c_int, c_int, POINTER(c_double), c_char_p]),
    'jme_jpl_close': (None, []),
    'jme_jpl_constant': (c_int, [c_char_p, POINTER(c_double), c_char_p]),
    'jme_jpl_constant_count': (c_int, [c_char_p]),
    'jme_jpl_constant_index': (c_int, [c_int, c_char_p, c_uint, POINTER(c_double), c_char_p]),
    'jme_jpl_constant_string': (c_int, [c_char_p, c_char_p, c_uint, c_char_p]),
    'jme_jpl_constant_string_vector': (c_int, [c_char_p, c_char_p, c_uint, c_int, c_char_p]),
    'jme_jpl_constant_vector': (c_int, [c_char_p, POINTER(c_double), c_int, c_char_p]),
    'jme_jpl_coverage': (c_int, [POINTER(c_double), POINTER(c_double), POINTER(c_int), c_char_p]),
    'jme_jpl_current_file_data': (c_int, [c_char_p, c_uint, POINTER(c_double), POINTER(c_double), POINTER(c_int), c_char_p]),
    'jme_jpl_ecliptic_state': (c_int, [c_double, c_int, c_int, c_int, POINTER(c_double), c_char_p]),
    'jme_jpl_ecliptic_state_naif': (c_int, [c_double, c_int, c_int, c_int, POINTER(c_double), c_char_p]),
    'jme_jpl_ecliptic_state_split': (c_int, [c_double, c_double, c_int, c_int, c_int, POINTER(c_double), c_char_p]),
    'jme_jpl_ecliptic_state_split_naif': (c_int, [c_double, c_double, c_int, c_int, c_int, POINTER(c_double), c_char_p]),
    'jme_jpl_ecliptic_state_utc': (c_int, [c_int, c_int, c_int, c_int, c_int, c_double, c_int, c_int, c_int, c_int, POINTER(c_double), c_char_p]),
    'jme_jpl_ecliptic_state_utc_naif': (c_int, [c_int, c_int, c_int, c_int, c_int, c_double, c_int, c_int, c_int, c_int, POINTER(c_double), c_char_p]),
    'jme_jpl_engine_version': (c_char_p, [c_char_p, c_size_t]),
    'jme_jpl_file': (c_char_p, []),
    'jme_jpl_file_version': (c_int, [c_char_p, c_uint, c_char_p]),
    'jme_jpl_id_by_name': (c_int, [c_char_p, POINTER(c_int), c_char_p]),
    'jme_jpl_is_available': (c_int, []),
    'jme_jpl_is_open': (c_int, []),
    'jme_jpl_is_thread_safe': (c_int, [c_char_p]),
    'jme_jpl_max_supported_order': (c_int, [c_int]),
    'jme_jpl_name_by_id': (c_int, [c_int, c_char_p, c_uint, c_char_p]),
    'jme_jpl_open': (c_int, [c_char_p, c_char_p]),
    'jme_jpl_open_array': (c_int, [c_int, POINTER(c_char_p), c_char_p]),
    'jme_jpl_orientation_record_count': (c_int, [c_char_p]),
    'jme_jpl_orientation_record_index': (c_int, [c_int, POINTER(c_int), POINTER(c_double), POINTER(c_double), POINTER(c_int), POINTER(c_int), c_char_p]),
    'jme_jpl_orientation_state_naif': (c_int, [c_double, c_int, c_int, POINTER(c_double), c_char_p]),
    'jme_jpl_orientation_state_order_naif': (c_int, [c_double, c_double, c_int, c_int, c_int, POINTER(c_double), c_char_p]),
    'jme_jpl_orientation_state_split_naif': (c_int, [c_double, c_double, c_int, c_int, POINTER(c_double), c_char_p]),
    'jme_jpl_orientation_state_utc_naif': (c_int, [c_int, c_int, c_int, c_int, c_int, c_double, c_int, c_int, c_int, POINTER(c_double), c_char_p]),
    'jme_jpl_position_record_count': (c_int, [c_char_p]),
    'jme_jpl_position_record_index': (c_int, [c_int, POINTER(c_int), POINTER(c_int), POINTER(c_double), POINTER(c_double), POINTER(c_int), POINTER(c_int), c_char_p]),
    'jme_jpl_prefetch': (c_int, [c_char_p]),
    'jme_jpl_rotational_angular_momentum_state_naif': (c_int, [c_double, c_int, c_int, POINTER(c_double), c_char_p]),
    'jme_jpl_rotational_angular_momentum_state_order_naif': (c_int, [c_double, c_double, c_int, c_int, c_int, POINTER(c_double), c_char_p]),
    'jme_jpl_rotational_angular_momentum_state_split_naif': (c_int, [c_double, c_double, c_int, c_int, POINTER(c_double), c_char_p]),
    'jme_jpl_rotational_angular_momentum_state_utc_naif': (c_int, [c_int, c_int, c_int, c_int, c_int, c_double, c_int, c_int, c_int, POINTER(c_double), c_char_p]),
    'jme_jpl_timescale': (c_int, []),
    'jme_julian_day': (c_double, [c_int, c_int, c_int, c_double, c_int]),
    'jme_lat_to_lmt': (c_int, [c_double, c_double, POINTER(c_double), c_char_p]),
    'jme_library_path': (c_char_p, []),
    'jme_lmt_to_lat': (c_int, [c_double, c_double, POINTER(c_double), c_char_p]),
    'jme_lun_eclipse_how': (c_int, [c_double, c_int, POINTER(c_double), POINTER(c_double), c_char_p]),
    'jme_lun_eclipse_when': (c_int, [c_double, c_int, c_int, POINTER(c_double), c_int, c_char_p]),
    'jme_lun_eclipse_when_loc': (c_int, [c_double, c_int, POINTER(c_double), POINTER(c_double), POINTER(c_double), c_int, c_char_p]),
    'jme_lun_occult_when_glob': (c_int, [c_double, c_int, c_char_p, c_int, c_int, POINTER(c_double), c_int, c_char_p]),
    'jme_lun_occult_when_loc': (c_int, [c_double, c_int, c_char_p, c_int, POINTER(c_double), POINTER(c_double), POINTER(c_double), c_int, c_char_p]),
    'jme_lun_occult_where': (c_int, [c_double, c_int, c_char_p, c_int, POINTER(c_double), POINTER(c_double), c_char_p]),
    'jme_matrix_identity': (None, [POINTER(c_double)]),
    'jme_matrix_multiply': (None, [POINTER(c_double), POINTER(c_double), POINTER(c_double)]),
    'jme_matrix_rotate_x': (None, [c_double, POINTER(c_double)]),
    'jme_matrix_rotate_y': (None, [c_double, POINTER(c_double)]),
    'jme_matrix_rotate_z': (None, [c_double, POINTER(c_double)]),
    'jme_matrix_transform_state': (None, [POINTER(c_double), POINTER(c_double), POINTER(c_double)]),
    'jme_meeus_moon_state': (c_int, [c_double, POINTER(c_double)]),
    'jme_meeus_planet_state': (c_int, [c_double, c_int, POINTER(c_double)]),
    'jme_meeus_sun_state': (c_int, [c_double, POINTER(c_double)]),
    'jme_mooncross': (c_int, [c_double, c_double, c_int, POINTER(c_double), c_char_p]),
    'jme_mooncross_node': (c_int, [c_double, c_int, POINTER(c_double), c_char_p]),
    'jme_mooncross_node_ut': (c_int, [c_double, c_int, POINTER(c_double), c_char_p]),
    'jme_mooncross_ut': (c_int, [c_double, c_double, c_int, POINTER(c_double), c_char_p]),
    'jme_moshier_planet_state': (c_int, [c_double, c_int, POINTER(c_double)]),
    'jme_nod_aps': (c_int, [c_double, c_int, c_int, c_int, POINTER(c_double), c_char_p]),
    'jme_nod_aps_ut': (c_int, [c_double, c_int, c_int, c_int, POINTER(c_double), c_char_p]),
    'jme_orbit_max_min_true_distance': (c_int, [c_double, c_int, c_int, POINTER(c_double), POINTER(c_double), POINTER(c_double), POINTER(c_double), c_char_p]),
    'jme_pheno': (c_int, [c_double, c_int, c_int, POINTER(c_double), c_char_p]),
    'jme_pheno_ut': (c_int, [c_double, c_int, c_int, POINTER(c_double), c_char_p]),
    'jme_radian_midpoint': (c_double, [c_double, c_double]),
    'jme_radian_normalize': (c_double, [c_double]),
    'jme_radians_difference_signed': (c_double, [c_double, c_double]),
    'jme_radians_to_degrees': (c_double, [c_double]),
    'jme_rectangular_to_spherical_state': (c_int, [POINTER(c_double), POINTER(c_double)]),
    'jme_refract': (c_double, [c_double, c_double, c_double, c_int]),
    'jme_refract_extended': (c_double, [c_double, c_double, c_double, c_double, c_double, c_int, POINTER(c_double)]),
    'jme_reverse_julian_day': (None, [c_double, c_int, POINTER(c_int), POINTER(c_int), POINTER(c_int), POINTER(c_double)]),
    'jme_rise_trans': (c_int, [c_double, c_int, c_char_p, c_int, c_int, POINTER(c_double), c_double, c_double, POINTER(c_double), c_char_p]),
    'jme_rise_trans_true_hor': (c_int, [c_double, c_int, c_char_p, c_int, c_int, POINTER(c_double), c_double, c_double, c_double, POINTER(c_double), c_char_p]),
    'jme_set_astro_models': (None, [c_char_p, c_int]),
    'jme_set_delta_t_userdef': (None, [c_double]),
    'jme_set_ephemeris_path': (None, [c_char_p]),
    'jme_set_interpolate_nut': (None, [c_int]),
    'jme_set_jpl_file': (None, [c_char_p]),
    'jme_set_lapse_rate': (None, [c_double]),
    'jme_set_sidereal_mode': (None, [c_int, c_double, c_double]),
    'jme_set_tid_acc': (None, [c_double]),
    'jme_set_topo': (None, [c_double, c_double, c_double]),
    'jme_sidereal_time': (c_double, [c_double]),
    'jme_sidereal_time0': (c_double, [c_double, c_double, c_double]),
    'jme_sol_eclipse_how': (c_int, [c_double, c_int, POINTER(c_double), POINTER(c_double), c_char_p]),
    'jme_sol_eclipse_when_glob': (c_int, [c_double, c_int, c_int, POINTER(c_double), c_int, c_char_p]),
    'jme_sol_eclipse_when_loc': (c_int, [c_double, c_int, POINTER(c_double), POINTER(c_double), POINTER(c_double), c_int, c_char_p]),
    'jme_sol_eclipse_where': (c_int, [c_double, c_int, POINTER(c_double), POINTER(c_double), c_char_p]),
    'jme_solcross': (c_int, [c_double, c_double, c_int, POINTER(c_double), c_char_p]),
    'jme_solcross_ut': (c_int, [c_double, c_double, c_int, POINTER(c_double), c_char_p]),
    'jme_spherical_angular_separation': (c_double, [c_double, c_double, c_double, c_double]),
    'jme_spherical_position_angle': (c_double, [c_double, c_double, c_double, c_double]),
    'jme_spherical_to_rectangular_state': (c_int, [POINTER(c_double), POINTER(c_double)]),
    'jme_split_degree': (None, [c_double, c_int, POINTER(c_int), POINTER(c_int), POINTER(c_int), POINTER(c_double), POINTER(c_int)]),
    'jme_state_add': (c_int, [POINTER(c_double), POINTER(c_double), POINTER(c_double)]),
    'jme_state_convert_units': (c_int, [POINTER(c_double), c_int, c_int, POINTER(c_double)]),
    'jme_state_distance': (c_double, [POINTER(c_double)]),
    'jme_state_light_time_days': (c_double, [POINTER(c_double), c_int]),
    'jme_state_position_velocity_dot': (c_double, [POINTER(c_double)]),
    'jme_state_scale': (c_int, [POINTER(c_double), c_double, POINTER(c_double)]),
    'jme_state_speed': (c_double, [POINTER(c_double)]),
    'jme_state_subtract': (c_int, [POINTER(c_double), POINTER(c_double), POINTER(c_double)]),
    'jme_time_equ': (c_int, [c_double, POINTER(c_double), c_char_p]),
    'jme_topo_arcus_visionis': (c_double, [c_double, POINTER(c_double), POINTER(c_double), c_char_p]),
    'jme_utc_time_zone': (None, [c_int, c_int, c_int, c_int, c_int, c_double, c_double, POINTER(c_int), POINTER(c_int), POINTER(c_int), POINTER(c_int), POINTER(c_int), POINTER(c_double)]),
    'jme_utc_to_jd': (c_int, [c_int, c_int, c_int, c_int, c_int, c_double, c_int, POINTER(c_double)]),
    'jme_version': (c_char_p, [c_char_p, c_size_t]),
    'jme_vis_limit_mag': (c_int, [c_double, POINTER(c_double), POINTER(c_double), c_char_p]),
    'jme_vsop87_planet_state': (c_int, [c_double, c_int, POINTER(c_double)]),
}


class JmeEph:
    """Direct runtime-FFI loader for the native JME shared library."""

    def __init__(self, library_path: str | Path | None = None) -> None:
        self._calceph = load_calceph_runtime()
        self.library_path = Path(library_path) if library_path is not None else find_library()
        self._lib = CDLL(str(self.library_path))
        self._configure_signatures()

    @property
    def lib(self) -> CDLL:
        """Return the underlying ctypes CDLL handle."""
        return self._lib

    def _configure_signatures(self) -> None:
        for name, (restype, argtypes) in _SIGNATURES.items():
            fn = getattr(self._lib, name)
            fn.restype = restype
            fn.argtypes = argtypes

    def __getattr__(self, name: str):
        if name in _SIGNATURES:
            return getattr(self._lib, name)
        raise AttributeError(name)


def signature_names() -> Iterable[str]:
    """Return all configured JME C function names."""

    return _SIGNATURES.keys()


__all__ = [
    "JmeEph",
    "signature_names",
    "byref",
    "create_string_buffer",
    "c_char",
    "c_char_p",
    "c_double",
    "c_int",
    "c_size_t",
    "c_uint",
    "POINTER",
]
